---
title: "NPS_hbarplot"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{NPS_hbarplot}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(SatisfiRe)
```


## NPS_hbarplot

Fonction qui permet plusieurs barplot horizontale représentant la propotion de promoteurs, neutres, détracteurs.

```{r}
NPS_hbarplot<- function(dataset,dr,reco){

grouped_data <- dplyr::group_by({{dataset}}, {{dr}})

summarize_data <-
  dplyr::summarize(
    grouped_data,
    promoteurs = sum({{reco}} >= 9),
    neutres = sum({{reco}} == 8 |
                    {{reco}} == 7),
    detracteurs = sum({{reco}} <= 6)
  )

contigence = as.data.frame(summarize_data)
row.names(contigence) = contigence$dr
contigence$dr <- NULL
contigence = as.data.frame(contigence)


A = contigence
B = A
A = round(A / rowSums(A), 2)





#A et B sont des dataframe ou chaque row.names est soit promoteur, neutre, détracteurs , chaque colonnes est un périmetres
# A est une propotion, B est une contingence


fig <-
  plotly::plot_ly(
    A,
    y = row.names(A),
    x = A$promoteurs ,
    text = A$promoteurs,
    textposition = 'auto' ,
    type = 'bar',
    orientation = 'h',
    name = 'Promoteurs',
    hovertext  = B$promoteurs,
    marker = list(color = "#4e9c34",
                  line = list(color = "#4e9c34",
                              width = 3))
  )


fig <-
  plotly::add_trace(
    fig,
    x = A$neutres,
    name = 'Neutres',
    text = A$neutres,
    textposition = 'auto',
    hovertext  = B$neutres,
    marker = list(color = "#fbb829",
                  line = list(color = "#fbb829",
                              width = 3))
  )

fig <-
  plotly::add_trace(
    fig,
    x = A$detracteurs,
    name = 'Détracteurs',
    text = A$detracteurs,
    textposition = 'auto',
    hovertext  = B$detracteurs,
    marker = list(color = '#bd3131',
                  line = list(color = '#bd3131',
                              width = 3))
  )

fig <- fig %>% plotly::layout(
  barmode = 'stack',
  xaxis = list(title = ""),
  yaxis = list(title = "")
)
return(fig)

}

```
 
 
